# Generated by Django 5.1.6 on 2025-03-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_brand_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='nmae',
            new_name='name',
        ),
    ]
